source "https://rubygems.org"

gem "opp", github: "jodydawkins/opp-ruby", ref: "b69cf26bf07e8ee3b0b54cb79cd0f453f2101073"
gem "puma", "~> 7.0"
gem "rackup", "~> 2.2"
gem "sinatra", "~> 4.2"
gem "sqlite3", "~> 2.7"

group :test do
  gem "minitest", "~> 5.25"
  gem "rack-test", "~> 2.2"
end
