source "https://rubygems.org"

gem "open-presence", "~> 0.1.0"
gem "puma", "~> 7.0"
gem "rackup", "~> 2.2"
gem "sinatra", "~> 4.2"
gem "sqlite3", "~> 2.7"

group :test do
  gem "minitest", "~> 5.25"
  gem "rack-test", "~> 2.2"
  gem "rake", "~> 13.2"
end
